package ua.nure.tatarinov.SummaryTask4.db;


/**
 * Contains all queries
 */
public class Query {

    //Select_as queries
    public static final String SELECT_USER_AS_STUDENT =     "SELECT * FROM USERS INNER JOIN STUDENTS ON STUDENTS.ID_USER = USERS.ID_USER WHERE LOGIN=?";
    public static final String SELECT_USER_AS_LECTURER =    "SELECT * FROM USERS INNER JOIN LECTURERS ON LECTURERS.ID_USER = USERS.ID_USER WHERE LOGIN=?";
    public static final String SELECT_USER_AS_ADMIN =       "SELECT * FROM USERS INNER JOIN ADMINS ON ADMINS.ID_USER = USERS.ID_USER WHERE LOGIN=?";

    //Simple select queries
    public static final String SELECT_ALL_USERS =           "SELECT * FROM USERS";
    public static final String SELECT_ALL_THEMES =          "SELECT * FROM THEMES";
    public static final String SELECT_ALL_LECTURERS =       "SELECT * FROM LECTURERS";
    public static final String SELECT_ALL_STATUSES =        "SELECT * FROM STATUSES";
    public static final String SELECT_ALL_COURSES =         "SELECT * FROM COURSES";
    public static final String SELECT_ALL_STUDENTS =        "SELECT * FROM STUDENTS";
    public static final String SELECT_ALL_STUDENT_ON_COURSE="SELECT * FROM STUDENT_COURSE";
    public static final String SELECT_ALL_DEFINITE_COURSE = "SELECT * FROM COURSES WHERE ID_COURSE=?";
    public static final String SELECT_STUDENT_BY_ID_USER =  "SELECT * FROM STUDENTS WHERE ID_USER=?";
    public static final String SELECT_USER_BY_LOGIN =       "SELECT * FROM USERS WHERE LOGIN = ?";

    //Complex select queries
    public static final String SELECT_STUDENT_MARK_BY_ID =                              "SELECT mark, JOURNAL.id_student_course FROM JOURNAL INNER JOIN STUDENT_COURSE ON JOURNAL.id_student_course = STUDENT_COURSE.id_student_course INNER JOIN STUDENTS ON STUDENT_COURSE.id_student = STUDENTS.id WHERE JOURNAL.ID_STUDENT_COURSE=?";
    public static final String SELECT_LAST_LECTURER_ID =                                "SELECT MAX(ID) FROM LECTURERS";
    public static final String SELECT_LAST_USER_ID =                                    "SELECT MAX(ID_USER) FROM USERS";
    public static final String SELECT_STUDENTS_AND_STATES =                             "SELECT USERS.ID_USER, SURNAME, NAME, PATRONYMIC, LOGIN, PASSWORD, NAME_STATE FROM STUDENTS INNER JOIN USERS ON STUDENTS.id_user = USERS.id_user INNER JOIN STATES ON USERS.id_state = STATES.id_state";
    public static final String SELECT_STUDENT_FROM_JOURNAL =                            "SELECT surname, name, patronymic, mark FROM JOURNAL INNER JOIN STUDENT_COURSE ON STUDENT_COURSE.id_student_course = JOURNAL.id_student_course INNER JOIN STUDENTS ON STUDENTS.ID=STUDENT_COURSE.ID_STUDENT WHERE JOURNAL.ID_STUDENT_COURSE=?";
    public static final String SELECT_COURSES_NOT_BEEN_REGISTERED =                     "SELECT * FROM COURSES WHERE name_course NOT IN( SELECT name_course FROM STUDENTS INNER JOIN STUDENT_COURSE ON STUDENTS.id = STUDENT_COURSE.id_student INNER JOIN COURSES ON COURSES.id_course = STUDENT_COURSE.id_course WHERE ID=?) AND id_status=1 ORDER BY name_course";
    public static final String SELECT_ALL_INFO_ABOUT_COURSES =                          "SELECT NAME_COURSE, DURATION, NAME_THEME, SURNAME, NAME, PATRONYMIC, NAME_STATUS, count(id_student_course) as COUNT FROM COURSES INNER JOIN THEMES ON THEMES.ID_THEME=COURSES.ID_THEME INNER JOIN LECTURERS ON LECTURERS.ID=COURSES.ID_LECTURER  INNER JOIN STATUSES ON STATUSES.ID_STATUS=COURSES.ID_STATUS INNER JOIN STUDENT_COURSE ON COURSES.id_course = STUDENT_COURSE.id_course GROUP BY NAME_COURSE, DURATION, NAME_THEME, SURNAME, NAME, PATRONYMIC, NAME_STATUS\n";
    public static final String SELECT_INFO_ABOUT_STUDENTS_FROM_LECTURER =               "SELECT JOURNAL.id_student_course, STUDENTS.id, login, name_course, duration, STUDENTS.name, STUDENTS.surname, STUDENTS.patronymic, mark FROM LECTURERS INNER JOIN USERS ON LECTURERS.id_user = USERS.id_user INNER JOIN COURSES ON LECTURERS.id = COURSES.id_lecturer INNER JOIN STUDENT_COURSE ON COURSES.id_course = STUDENT_COURSE.id_course INNER JOIN JOURNAL ON STUDENT_COURSE.id_student_course = JOURNAL.id_student_course INNER JOIN STUDENTS ON STUDENT_COURSE.id_student = STUDENTS.id WHERE login = ?";
    public static final String SELECT_INFO_ABOUT_COURSE_BY_LOGIN_AND_BY_COURSE_STATUS = "SELECT NAME_COURSE, DURATION, THEMES.NAME_THEME, LECTURERS.SURNAME, LECTURERS.NAME, LECTURERS.PATRONYMIC FROM STUDENTS INNER JOIN STUDENT_COURSE ON STUDENT_COURSE.ID_STUDENT=STUDENTS.ID INNER JOIN COURSES ON STUDENT_COURSE.ID_COURSE=COURSES.ID_COURSE INNER JOIN STATUSES ON STATUSES.ID_STATUS = COURSES.ID_STATUS INNER JOIN THEMES ON COURSES.ID_THEME = THEMES.ID_THEME INNER JOIN LECTURERS ON COURSES.ID_LECTURER = LECTURERS.ID INNER JOIN USERS ON USERS.ID_USER = STUDENTS.ID_USER WHERE USERS.LOGIN = ? AND STATUSES.NAME_STATUS = ?";
    public static final String SELECT_PROGRESS_BY_USER =                                "SELECT NAME_COURSE, LECTURERS.SURNAME, LECTURERS.NAME, LECTURERS.PATRONYMIC, MARK FROM STUDENTS INNER JOIN STUDENT_COURSE ON STUDENTS.ID = STUDENT_COURSE.ID_STUDENT INNER JOIN COURSES ON STUDENT_COURSE.ID_COURSE = COURSES.ID_COURSE INNER JOIN STATUSES ON COURSES.ID_STATUS = STATUSES.ID_STATUS INNER JOIN JOURNAL ON STUDENT_COURSE.ID_STUDENT_COURSE = JOURNAL.ID_STUDENT_COURSE INNER JOIN LECTURERS ON COURSES.ID_LECTURER = LECTURERS.ID INNER JOIN USERS ON STUDENTS.ID_USER = USERS.ID_USER WHERE STATUSES.ID_STATUS = 4 AND USERS.LOGIN=?";
    public static final String SELECT_COUNT_STUDENTS_PER_COURSE =                       "SELECT COUNT(ID_STUDENT_COURSE), ID_COURSE FROM STUDENT_COURSE GROUP BY ID_COURSE";

    //Search queries
    public static final String FIND_STUDENT_BY_STRING =     "SELECT * FROM STUDENTS WHERE UCASE(SURNAME) LIKE UCASE(?) OR NAME LIKE UCASE(?) OR PATRONYMIC LIKE UCASE(?)";
    public static final String FIND_LECTURER_BY_STRING =    "SELECT * FROM LECTURERS WHERE UPPER(SURNAME) LIKE UPPER(?) OR NAME LIKE UPPER(?) OR PATRONYMIC LIKE UPPER(?)";
    public static final String FIND_COURSE_BY_STRING =      "SELECT * FROM COURSES WHERE UPPER(NAME_COURSE) LIKE UPPER(?)";

    //Create queries
    public static final String CREATE_USER =                "INSERT INTO USERS          VALUES (DEFAULT, ?, ?, null, 2, 1)";
    public static final String CREATE_LECTURER =            "INSERT INTO LECTURERS      VALUES (DEFAULT, ?, ?, ?, ?)";
    public static final String CREATE_COURSE =              "INSERT INTO COURSES        VALUES (DEFAULT, ?, ?, ?, ?, ?)";
    public static final String REGISTER_USER_ON_COURSE=     "INSERT INTO STUDENT_COURSE VALUES (DEFAULT, ?, ?)";
    public static final String CREATE_MARK_FOR_STUDENT =    "INSERT INTO JOURNAL VALUES(?, ?)";

    //Update queries
    public static final String UPDATE_STUDENT =     "UPDATE STUDENTS    SET SURNAME = ?, NAME = ?, PATRONYMIC = ? WHERE ID_USER = ?";
    public static final String UPDATE_LECTURER =    "UPDATE LECTURERS   SET SURNAME = ?, NAME = ?, PATRONYMIC = ? WHERE ID_USER = ?";
    public static final String UPDATE_ADMIN =       "UPDATE ADMINS      SET SURNAME = ?, NAME = ?, PATRONYMIC = ? WHERE ID_USER = ?";
    public static final String UPDATE_USER =        "UPDATE USERS       SET LOGIN = ?, EMAIL = ? WHERE ID_USER = ?";
    public static final String UPDATE_JOURNAL =     "UPDATE JOURNAL     SET MARK = ? WHERE ID_STUDENT_COURSE = ?";
    public static final String UPDATE_COURSE =      "UPDATE COURSES     SET NAME_COURSE=?, DURATION=?, ID_THEME=?,ID_LECTURER=?,ID_STATUS=? WHERE ID_COURSE=?";
    public static final String UPDATE_PASSWORD =    "UPDATE USERS       SET PASSWORD = ? WHERE ID_USER = ?";
    public static final String CHANGE_STATE_USER =  "UPDATE USERS       SET ID_STATE = ? WHERE ID_USER = ?";
    public static final String CHANGE_LECTURER =    "UPDATE COURSES     SET ID_LECTURER = ? WHERE ID_COURSE = ?";

    //Delete queries
    public static final String DELETE_COURSE =      "DELETE FROM COURSES WHERE ID_COURSE=?";

    //
    public static final String TOP_MARK = "SELECT NAME_COURSE, MAX(MARK) FROM STUDENTS INNER JOIN STUDENT_COURSE ON STUDENTS.id = STUDENT_COURSE.id_student INNER JOIN JOURNAL ON STUDENT_COURSE.id_student_course = JOURNAL.id_student_course INNER JOIN COURSES ON STUDENT_COURSE.id_course = COURSES.id_course GROUP BY NAME_COURSE ORDER BY MAX(MARK) DESC";
    public static final String AVG_MARK = "SELECT surname, name, patronymic, AVG(mark) FROM STUDENTS INNER JOIN STUDENT_COURSE ON STUDENTS.id = STUDENT_COURSE.id_student INNER JOIN JOURNAL ON STUDENT_COURSE.id_student_course = JOURNAL.id_student_course GROUP BY surname, name, patronymic ORDER BY AVG(MARK) DESC";
}
